### ISSUE TITLE
Upstream generalizable code to kubernetes/kubectl

### ISSUE THREAD

**Issue by arschles** [Azure/service-catalog-cli#64]
At Kubecon 2017 in Austin, I talked with @pwittrock about this CLI and he suggested that we upstream some of our generalizable code (i.e. parsing a kube config file) to https://github.com/kubernetes/kubectl.

@mbauer and @jberkhahn were also at that discussion, and they have written a set of Kubectl plugins that also contain some generalizable code (naturally, service-catalog-cli and the plugins duplicate a lot of functionality)

The end state should be that as much generalizable code is pushed upstream and this CLI pulls it in.

cc/ @carolynvs

**Comment by jberkhahn** [comment]
I'm working on this, extracting the library I've been working on [here](http://github.com/jberkhahn/service-catalog-plugins).
