### ISSUE TITLE
Add command to check if the cluster is service catalog ready

### ISSUE THREAD

**Issue by carolynvs** [Azure/service-catalog-cli#66]
Perform a set of validations against the current cluster to validate that they are "service catalog ready": 
* Make sure that Tiller is ready to install cluster-global resources
* Make sure the cluster has RBAC turned on
* Make sure the cluster has support for aggregated APIs
* Actually do the helm install? Maybe we can skip this at first and add it later

This would help with troubleshooting why the service catalog install isn't working too.

_Copy/pasted from @arschles brain_

**Comment by arschles** [comment]
Note that there is some prior art [here](https://github.com/GoogleCloudPlatform/k8s-service-catalog)
